# Generated by Django 5.2.17 on 2026-08-11 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='datos_anteriores',
            field=models.JSONField(blank=True, help_text='Estado del registro antes de ser modificado o eliminado', null=True, verbose_name='Datos Anteriores (JSON)'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='datos_nuevos',
            field=models.JSONField(blank=True, help_text='Estado del registro después del cambio o registro recién creado', null=True, verbose_name='Datos Nuevos (JSON)'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Acción'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='registro_id',
            field=models.BigIntegerField(blank=True, help_text='Llave primaria (ID) del registro auditado', null=True, verbose_name='ID de Registro Afectado'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tabla_afectada',
            field=models.CharField(help_text='Nombre de la entidad o tabla modificada (ej. cliente, lote, contrato)', max_length=100, verbose_name='Tabla Afectada'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cui',
            field=models.CharField(help_text='Número de documento de identificación (13 dígitos sin espacios)', max_length=13, unique=True, verbose_name='CUI / DPI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario asignada si el cliente tiene acceso al portal web', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema Asociado'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Explicación detallada de las funciones asignadas a este rol', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(help_text='Nombre único del rol (ej. Administrador, Asesor Comercial)', max_length=50, unique=True, verbose_name='Nombre de Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Dirección de correo electrónico única del usuario', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol asignado dentro del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cuentas.rol', verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número telefónico personal o laboral', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
