# Generated by Django 5.2.17 on 2026-08-18 21:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEspacio',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Estado')),
                ('nombre_estado', models.CharField(help_text='Estado operacional (ej. Disponible, Reservado, Ocupado, Mantenimiento)', max_length=50, unique=True, verbose_name='Nombre del Estado')),
                ('codigo_color_hex', models.CharField(help_text='Código hexadecimal de color para interfaz gráfica 2D (ej. #28A745)', max_length=7, verbose_name='Código Color HEX')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Espacio',
                'verbose_name_plural': 'Estados de Espacio',
                'db_table': 'inventario_estado_espacio',
                'ordering': ['id_estado'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Sector')),
                ('nombre_sector', models.CharField(help_text='Nombre descriptivo del sector (ej. Sector A - Jardines de Paz)', max_length=100, unique=True, verbose_name='Nombre del Sector')),
                ('nomenclatura', models.CharField(help_text='Código corto o sigla del sector (ej. SEC-A)', max_length=20, unique=True, verbose_name='Nomenclatura')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles o ubicación de la zona dentro del cementerio', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'inventario_sector',
                'ordering': ['nombre_sector'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstructura',
            fields=[
                ('id_tipo_estructura', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Tipo Estructura')),
                ('nombre_tipo', models.CharField(help_text='Clasificación de construcción (ej. Pabellón, Mausoleo, Capilla)', max_length=50, unique=True, verbose_name='Nombre de Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Estructura',
                'verbose_name_plural': 'Tipos de Estructura',
                'db_table': 'inventario_tipo_estructura',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraFisica',
            fields=[
                ('id_estructura', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Estructura')),
                ('nombre_estructura', models.CharField(help_text='Ejemplo: Pabellón San José', max_length=100, verbose_name='Nombre de Estructura')),
                ('codigo_estructura', models.CharField(help_text='Código único identicador de la estructura (ej. PAB-01)', max_length=50, unique=True, verbose_name='Código de Estructura')),
                ('total_filas', models.PositiveIntegerField(help_text='Número total de filas / alto en la grilla 2D', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Filas (Y)')),
                ('total_columnas', models.PositiveIntegerField(help_text='Número total de columnas / ancho en la grilla 2D', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Columnas (X)')),
                ('capacidad_total_espacios', models.PositiveIntegerField(editable=False, help_text='Calculado automáticamente (filas * columnas)', verbose_name='Capacidad Total de Espacios')),
                ('precio_estructura_completa', models.DecimalField(blank=True, decimal_places=2, help_text='Aplica para venta global de mausoleos o capillas completas', max_digits=12, null=True, verbose_name='Precio Estructura Completa')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.sector', verbose_name='Sector')),
                ('tipo_estructura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.tipoestructura', verbose_name='Tipo de Estructura')),
            ],
            options={
                'verbose_name': 'Estructura Física',
                'verbose_name_plural': 'Estructuras Físicas',
                'db_table': 'inventario_estructura_fisica',
                'ordering': ['sector', 'nombre_estructura'],
            },
        ),
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('id_espacio', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Espacio')),
                ('codigo_unico_espacio', models.CharField(blank=True, help_text='Auto-generado: [SECTOR]-[ESTRUCTURA]-F[FILA]-C[COLUMNA]', max_length=100, unique=True, verbose_name='Código Único de Espacio')),
                ('posicion_fila', models.PositiveIntegerField(help_text='Número de fila dentro de la estructura (1..total_filas)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Posición Fila (Y)')),
                ('posicion_columna', models.PositiveIntegerField(help_text='Número de columna dentro de la estructura (1..total_columnas)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Posición Columna (X)')),
                ('dimensiones', models.CharField(default='2.20m x 0.90m x 0.80m', help_text='Largo x Ancho x Alto', max_length=50, verbose_name='Dimensiones')),
                ('material_construccion', models.CharField(default='Concreto Reforzado', max_length=100, verbose_name='Material de Construcción')),
                ('precio_individual', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta por nicho individual', max_digits=12, null=True, verbose_name='Precio Individual')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='inventario.estadoespacio', verbose_name='Estado del Espacio')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='inventario.estructurafisica', verbose_name='Estructura Física')),
            ],
            options={
                'verbose_name': 'Espacio Físico',
                'verbose_name_plural': 'Espacios Físicos',
                'db_table': 'inventario_espacio_fisico',
                'ordering': ['estructura', 'posicion_fila', 'posicion_columna'],
                'constraints': [models.UniqueConstraint(fields=('estructura', 'posicion_fila', 'posicion_columna'), name='unique_posicion_por_estructura')],
            },
        ),
    ]
