# Generated by Django 5.2.17 on 2026-09-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('inventario', '0002_remove_estadoespacio_codigo_color_hex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Difunto')),
                ('cui', models.CharField(blank=True, help_text='Código Único de Identificación (13 dígitos). Opcional para recién nacidos sin CUI emitido por RENAP.', max_length=13, null=True, unique=True, verbose_name='CUI / DPI')),
                ('nombres', models.CharField(help_text='Nombres completos de la persona fallecida', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos completos de la persona fallecida', max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fecha_defuncion', models.DateField(verbose_name='Fecha de Defunción')),
                ('causa_muerte', models.CharField(help_text='Causa médica o legal del fallecimiento', max_length=200, verbose_name='Causa de Muerte')),
                ('lugar_defuncion', models.CharField(blank=True, help_text='Centro hospitalario, domicilio u otra ubicación', max_length=200, null=True, verbose_name='Lugar de Defunción')),
            ],
            options={
                'verbose_name': 'Difunto',
                'verbose_name_plural': 'Difuntos',
                'db_table': 'inhumaciones_difunto',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['cui'], name='idx_inhumaciones_difunto_cui')],
            },
        ),
        migrations.CreateModel(
            name='RegistroInhumacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Registro Inhumación')),
                ('fecha_sepelio', models.DateTimeField(verbose_name='Fecha y Hora de Sepelio')),
                ('acta_renap_pdf', models.FileField(help_text='Documento digitalizado del Acta de Defunción emitida por RENAP', upload_to='inhumaciones/actas_renap/', verbose_name='Acta de Defunción RENAP (PDF)')),
                ('certificado_mspas_pdf', models.FileField(blank=True, help_text='Documento de autorización sanitaria emitido por MSPAS (si aplica)', null=True, upload_to='inhumaciones/certificados_mspas/', verbose_name='Certificado MSPAS (PDF)')),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones operativas adicionales', null=True, verbose_name='Observaciones')),
                ('estado_inhumacion', models.CharField(choices=[('ACTIVA', 'Activa'), ('EXHUMADO', 'Exhumado'), ('TRASLADADO', 'Trasladado')], default='ACTIVA', max_length=20, verbose_name='Estado de Inhumación')),
                ('contrato', models.ForeignKey(help_text='Contrato de derechos de uso que autoriza el sepelio', on_delete=django.db.models.deletion.RESTRICT, related_name='inhumaciones', to='comercial.contrato', verbose_name='Contrato Comercial')),
                ('difunto', models.OneToOneField(help_text='Persona fallecida objeto de la inhumación', on_delete=django.db.models.deletion.RESTRICT, related_name='registro_inhumacion', to='inhumaciones.difunto', verbose_name='Difunto')),
                ('espacio', models.ForeignKey(help_text='Nicho o espacio físico asignado en el camposanto', on_delete=django.db.models.deletion.RESTRICT, related_name='inhumaciones', to='inventario.espaciofisico', verbose_name='Espacio Físico (Nicho)')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario del sistema que procesó el registro', on_delete=django.db.models.deletion.RESTRICT, related_name='inhumaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Operador / Registro')),
            ],
            options={
                'verbose_name': 'Registro de Inhumación',
                'verbose_name_plural': 'Registros de Inhumación',
                'db_table': 'inhumaciones_registro',
                'ordering': ['-fecha_sepelio'],
                'indexes': [models.Index(fields=['difunto'], name='idx_inhum_reg_difunto'), models.Index(fields=['espacio'], name='idx_inhum_reg_espacio'), models.Index(fields=['contrato'], name='idx_inhum_reg_contrato')],
            },
        ),
    ]
