# Generated by Django 5.2.17 on 2026-10-01 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhumaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinhumacion',
            name='acta_renap_pdf',
            field=models.FileField(help_text='Documento digitalizado del Acta de Defunción emitida por RENAP', upload_to='inhumaciones/actas_renap/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Acta de Defunción RENAP (PDF)'),
        ),
        migrations.AlterField(
            model_name='registroinhumacion',
            name='certificado_mspas_pdf',
            field=models.FileField(blank=True, help_text='Documento de autorización sanitaria emitido por MSPAS (si aplica)', null=True, upload_to='inhumaciones/certificados_mspas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificado MSPAS (PDF)'),
        ),
    ]
