# Generated by Django 5.2.17 on 2026-08-20 19:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_alter_bitacora_datos_anteriores_and_more'),
        ('inventario', '0002_remove_estadoespacio_codigo_color_hex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id_estado_contrato', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Estado Contrato')),
                ('nombre_estado_contrato', models.CharField(help_text='Ejemplo: Solicitado, Activo, Liquidado, Cancelado', max_length=40, unique=True, verbose_name='Nombre de Estado')),
            ],
            options={
                'verbose_name': 'Estado de Contrato',
                'verbose_name_plural': 'Estados de Contrato',
                'db_table': 'comercial_estado_contrato',
                'ordering': ['id_estado_contrato'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadVenta',
            fields=[
                ('id_modalidad', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Modalidad')),
                ('nombre_modalidad', models.CharField(help_text='Ejemplo: Contado, Crédito 24 Meses', max_length=50, unique=True, verbose_name='Nombre de Modalidad')),
                ('aplica_credito', models.BooleanField(default=True, help_text='Indica si la modalidad requiere generación de plan de cuotas de amortización', verbose_name='Aplica Crédito / Plazos')),
                ('descripcion', models.CharField(blank=True, help_text='Detalles comerciales de la modalidad', max_length=150, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Modalidad de Venta',
                'verbose_name_plural': 'Modalidades de Venta',
                'db_table': 'comercial_modalidad_venta',
                'ordering': ['id_modalidad'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Contrato')),
                ('numero_contrato', models.CharField(help_text='Código único del contrato de venta (ej. CNT-2026-0001)', max_length=30, unique=True, verbose_name='Número de Contrato')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Precio total de venta negociado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total (Q)')),
                ('monto_enganche', models.DecimalField(decimal_places=2, help_text='Monto aportado como pago inicial o enganche', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Enganche (Q)')),
                ('monto_financiar', models.DecimalField(decimal_places=2, help_text='Saldo neto a diferir a plazos (monto_total - monto_enganche)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto a Financiar (Q)')),
                ('plazo_meses', models.PositiveIntegerField(default=0, help_text='Número de meses pactados para la amortización del saldo', verbose_name='Plazo en Meses')),
                ('fecha_firma', models.DateField(default=datetime.date.today, verbose_name='Fecha de Firma del Contrato')),
                ('fecha_inicio_pago', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio de Primer Pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='cuentas.cliente', verbose_name='Cliente / Titular')),
                ('usuario_asesor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos_asesorados', to=settings.AUTH_USER_MODEL, verbose_name='Asesor Comercial / Vendedor')),
                ('estado_contrato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='comercial.estadocontrato', verbose_name='Estado de Contrato')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='comercial.modalidadventa', verbose_name='Modalidad de Venta')),
            ],
            options={
                'verbose_name': 'Contrato Comercial',
                'verbose_name_plural': 'Contratos Comerciales',
                'db_table': 'comercial_contrato',
                'ordering': ['-fecha_firma', '-id_contrato'],
            },
        ),
        migrations.CreateModel(
            name='ControlMantenimiento',
            fields=[
                ('id_control_mante', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Control Mantenimiento')),
                ('anio_periodo', models.PositiveIntegerField(help_text='Ejemplo: 2026', verbose_name='Año del Período')),
                ('monto_mantenimiento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Mantenimiento (Q)')),
                ('fecha_limite_pago', models.DateField(verbose_name='Fecha Límite de Pago')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('estado_cobro', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('EN_MORA', 'En Mora')], default='PENDIENTE', max_length=20, verbose_name='Estado de Cobro')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_mantenimientos', to='comercial.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Control de Mantenimiento Anual',
                'verbose_name_plural': 'Controles de Mantenimiento Anual',
                'db_table': 'comercial_control_mantenimiento',
                'ordering': ['-anio_periodo', 'contrato'],
            },
        ),
        migrations.CreateModel(
            name='DetalleContratoEspacio',
            fields=[
                ('id_detalle_contrato', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Contrato Espacio')),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta Unitario (Q)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_espacio', to='comercial.contrato', verbose_name='Contrato')),
                ('espacio', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='detalle_contrato', to='inventario.espaciofisico', verbose_name='Espacio Físico (Nicho)')),
            ],
            options={
                'verbose_name': 'Detalle Contrato Espacio',
                'verbose_name_plural': 'Detalles de Contrato - Espacios',
                'db_table': 'comercial_detalle_contrato_espacio',
                'ordering': ['id_detalle_contrato'],
            },
        ),
        migrations.CreateModel(
            name='PlanPagoCuota',
            fields=[
                ('id_plan', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Plan Cuota')),
                ('numero_cuota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto de Cuota (Q)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado_cuota', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('PARCIAL', 'Parcial'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20, verbose_name='Estado de Cuota')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cuotas', to='comercial.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Cuota de Plan de Pago',
                'verbose_name_plural': 'Cuotas de Plan de Pago',
                'db_table': 'comercial_plan_pago_cuota',
                'ordering': ['contrato', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id_recibo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Recibo')),
                ('correlativo_recibo', models.BigIntegerField(help_text='Número secuencial único impreso en el recibo de caja', unique=True, verbose_name='Correlativo de Recibo de Caja')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Transacción')),
                ('monto_ingresado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Ingresado (Q)')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEPOSITO_BANCO', 'Depósito Bancario'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta de Crédito / Débito')], default='EFECTIVO', max_length=30, verbose_name='Método de Pago')),
                ('numero_boleta_banco', models.CharField(blank=True, help_text='Requerido si el pago es transferencia, depósito o tarjeta', max_length=50, null=True, verbose_name='Número de Boleta / Referencia Bancaria')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones / Notas')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recibos_pago', to='comercial.contrato', verbose_name='Contrato')),
                ('usuario_cajero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recibos_cobrados', to=settings.AUTH_USER_MODEL, verbose_name='Cajero / Operador de Caja')),
            ],
            options={
                'verbose_name': 'Recibo de Pago (Caja)',
                'verbose_name_plural': 'Recibos de Pago (Caja)',
                'db_table': 'comercial_recibo_pago',
                'ordering': ['-fecha_transaccion', '-id_recibo'],
            },
        ),
        migrations.CreateModel(
            name='DetallePagoRecibo',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Recibo')),
                ('concepto', models.CharField(choices=[('ENGANCHE', 'Enganche Inicial'), ('CUOTA_AMORTIZACION', 'Cuota de Amortización'), ('MANTENIMIENTO_ANUAL', 'Mantenimiento Anual'), ('OTRO', 'Otro Concepto')], max_length=50, verbose_name='Concepto de Pago')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Aplicado (Q)')),
                ('control_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_recibo', to='comercial.controlmantenimiento', verbose_name='Control de Mantenimiento Saldado')),
                ('plan_cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_recibo', to='comercial.planpagocuota', verbose_name='Cuota de Plan de Amortización Saldada')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.recibopago', verbose_name='Recibo de Pago Maestro')),
            ],
            options={
                'verbose_name': 'Detalle de Pago en Recibo',
                'verbose_name_plural': 'Detalles de Pago en Recibo',
                'db_table': 'comercial_detalle_pago_recibo',
                'ordering': ['id_detalle'],
            },
        ),
        migrations.AddConstraint(
            model_name='controlmantenimiento',
            constraint=models.UniqueConstraint(fields=('contrato', 'anio_periodo'), name='uq_contrato_periodo_mante'),
        ),
        migrations.AddConstraint(
            model_name='planpagocuota',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero_cuota'), name='uq_contrato_num_cuota'),
        ),
    ]
