# Generated by Django 5.2.17 on 2026-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Código único del contrato de venta (ej. CNT-2026-0001)', max_length=30, unique=True, verbose_name='Número de Contrato'),
        ),
    ]
